USE OrderingCoffee;
GO

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    KullaniciAdi NVARCHAR(100) NOT NULL,
    Email NVARCHAR(200) NOT NULL UNIQUE,
    SifreHash NVARCHAR(500) NOT NULL
);
GO